### ISSUE TITLE
Uncaught AssertionError: Failed to find slider element for playback "#material-player-progress"

### ISSUE THREAD

**Issue by Spyruf** [twolfson/google-music.js#44] opened 2016-06-19 15:54 UTC
Sourcing gmuisc.js via vanilla but when I initiate the constructor in script tags or my JS file this error is thrown in the console

`window.gmusic = new window.GMusic(window); // Our Google Music API`

 I've looked at the code and tried to figure out what is is but it seems like a bug. If someone could help me find a workaround I'd appreciate it.

**Comment by MarshallOfSound** [comment] 2016-06-19 15:58
Basically you can't call `new GMusic(window)` until GMusic has loaded sufficiently for us to hook into certain DOM elements.

See #16 for more information

Also see https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/inject/GPMWebView/index.js#L32 for an example on how to wait till GPM is ready.

**Comment by twolfson** [comment] 2016-06-19 16:01
Closing this as a duplicate of #16 for now.

**Comment by Spyruf** [comment] 2016-06-19 16:02
It seemed like a similar issue to that post, I wasn't sure. Thanks for clearing things up, I'll try one of the retry libraries you suggested.

**Closed as completed by twolfson** 2016-06-19 16:01 UTC
Labels: duplicate
